### ISSUE TITLE
Error message during reboot

### ISSUE THREAD

**Issue by cdupont** [Waziup/WaziGate#68]
This message appears when I reboot:
```
2020-02-27T06:27:48.956036018Z [Info  ] System reboot
2020-02-27T06:27:50.251733896Z http: panic serving [::1]:59196: runtime error: invalid memory address or nil pointer dereference
2020-02-27T06:27:50.251855645Z goroutine 171 [running]:
2020-02-27T06:27:50.251888295Z net/http.(*conn).serve.func1(0x1149da0)
2020-02-27T06:27:50.251925841Z 	/usr/lib/go/src/net/http/server.go:1767 +0xfc
2020-02-27T06:27:50.251954742Z panic(0x8f1040, 0xaf1e98)
2020-02-27T06:27:50.251985934Z 	/usr/lib/go/src/runtime/panic.go:679 +0x1a0
2020-02-27T06:27:50.252014158Z periph.io/x/periph/devices/ssd1306.(*Dev).Halt(0x0, 0x0, 0x0)
2020-02-27T06:27:50.252042226Z 	/go/pkg/mod/periph.io/x/periph@v3.6.2+incompatible/devices/ssd1306/ssd1306.go:256 +0x18
2020-02-27T06:27:50.252077845Z github.com/Waziup/wazigate-system/api.oledHalt()
2020-02-27T06:27:50.252108881Z 	/go/src/github.com/Waziup/wazigate-system/api/oled.go:88 +0x68
2020-02-27T06:27:50.252137626Z github.com/Waziup/wazigate-system/api.systemShutdown(0x7a3849, 0x6)
2020-02-27T06:27:50.252165746Z 	/go/src/github.com/Waziup/wazigate-system/api/system.go:198 +0x1bc
2020-02-27T06:27:50.252194959Z github.com/Waziup/wazigate-system/api.SystemReboot(0x93aa90, 0x1315290, 0x1108b80, 0x0, 0x0, 0x0)
2020-02-27T06:27:50.252224485Z 	/go/src/github.com/Waziup/wazigate-system/api/system.go:172 +0x28
2020-02-27T06:27:50.252252657Z github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x106e150, 0x93aa90, 0x1315290, 0x1108b80)
2020-02-27T06:27:50.252288901Z 	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x91c
2020-02-27T06:27:50.252318271Z net/http.serverHandler.ServeHTTP(0x107a990, 0x93aa90, 0x1315290, 0x1108b80)
2020-02-27T06:27:50.252347692Z 	/usr/lib/go/src/net/http/server.go:2802 +0x90
2020-02-27T06:27:50.252376021Z net/http.(*conn).serve(0x1149da0, 0x93b030, 0x1311240)
2020-02-27T06:27:50.252403828Z 	/usr/lib/go/src/net/http/server.go:1890 +0x848
2020-02-27T06:27:50.252432104Z created by net/http.(*Server).Serve
2020-02-27T06:27:50.252482668Z 	/usr/lib/go/src/net/http/server.go:2927 +0x334
```

**Comment by mojtaba-esk** [comment]
This was due to lack of OLED, now fixed. Thanks
