### ISSUE TITLE
Docker corrupted after improper shutdown

### ISSUE THREAD

**Issue by j-forster** [Waziup/WaziGate#71]
Some times, when the Raspberry Pi is unplugged without proper shutdown, Docker gets corrupted.
This is a major issue as users tend to unsafely unplug the Raspberry Pi. Another case would be a general power outage that affects the Pi.

After the restart, **all** docker commands fail:

```
pi@raspberrypi:~ $ docker
SIGILL: illegal instruction
PC=0x8d1328 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.initsig(0x0)
        /usr/local/go/src/runtime/signal_unix.go:107 +0x104 fp=0x545a774 sp=0x545a74c pc=0x8d1328
runtime: unexpected return pc for runtime.mapassign_faststr called from 0x24
stack: frame={sp:0x545a774, fp:0x545a7a4} stack=[0x545a000,0x545a800)
0545a6f4:  00000000  00000360  76dcc301  054a6000
0545a704:  0000001c  036901d8  000000cc  76dcc368
0545a714:  00000000  76dd6b08  054a4000  0089555c <runtime.newobject+44>
0545a724:  036901d8  00894c64 <runtime.mallocgc+744>  00896644 <runtime.makeBucketArray+408>  00000380
0545a734:  02502a38  00000001  054a6000  00896370 <runtime.makemap+248>
0545a744:  02502a38  00000008  0089c3fc <runtime.mapassign_faststr+88>  009016e0 <unicode.init.ializers+112>
0545a754:  0545a78c  ce04590e  009016a0 <unicode.init.ializers+48>  02454dc8
0545a764:  054a4003  00000000  054a6000  00000000
0545a774: <00000024  00000000  00000001  00908350 <unicode.init+72>
0545a784:  02454dc8  054a4000  01cc9f1f  00000001
0545a794:  00000008  024426b8  00900360 <sync.init.1+28>  054a2010
0545a7a4: >0090032c <sync.init.0+32>  03614e88  054a4000  0091eb2c <reflect.init+84>
0545a7b4:  0092a624 <internal/fmtsort.init+72>  00970ac0 <fmt.init+76>  01cc4460 <main.init+72>  008bc504 <runtime.main+512>
0545a7c4:  008ea368 <runtime.goexit+4>  01cc4a40  00000000  00000000
0545a7d4:  00000000  00000001  00000000  054000e0
0545a7e4:  00000000  76fdaaa0  00000001  00000000
0545a7f4:  00000000  00000000  00000000
runtime.mapassign_faststr(0x3614e88, 0x54a4000, 0x91eb2c, 0x92a624, 0x970ac0)
        /usr/local/go/src/runtime/map_faststr.go:214 +0x58 fp=0x545a7a4 sp=0x545a774 pc=0x89c3fc

trap    0x6
error   0x0
oldmask 0x0
r0      0x0
r1      0x2454dc8
r2      0x1ce7a3f
r3      0x545a78c
r4      0x1
r5      0x3
r6      0xff
r7      0x265ffa0
r8      0x3
r9      0x380
r10     0x54000e0
fp      0x3611678
ip      0xd8
sp      0x545a74c
lr      0x89c3fc
pc      0x8d1328
cpsr    0x40000030
fault   0x12
```

Reinstall docker doesn't work:

```
pi@raspberrypi:~ $ curl -sSL https://get.docker.com | sh
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1

  {{ SAME ERROR AS ABOVE }}

sh: 219: [: Illegal number:
sh: 223: [: Illegal number:
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sudo -E sh -c docker version

  {{ SAME ERROR AS ABOVE }}

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker pi

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
```

**Comment by j-forster** [comment]
I will closed this issue as it might be outside of the scope of the Wazigate software.
